[project]
name = "hackathonfoundations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "moviepy>=1.0.3",
    "openai>=1.101.0",
    "python-dotenv>=1.1.1"
]
